name: Monitor bot PRs [Test only]

# description: |
# This workflow mimics how a go-openapi repo would typically invoke the common workflow.

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: ./.github/workflows/monitor-bot-pr.yml
    secrets: inherit
