name: doc update check
# description: This workflow mimics how a go-openapi repo would typically invoke the common workflow.

on:
  pull_request:
    paths:
    - '**/*.md'

permissions:
  pull-requests: read
  contents: read

jobs:
  test:
    uses: ./.github/workflows/doc-update.yml
    secrets: inherit
