name: Markdown changed

on:
  workflow_call:

permissions:
  contents: read

jobs:
  markdown-changed:
    # description: |
    # This triggers a markdown and spellcheck lint whenever documentation files change.
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.changed-markdown-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
    steps:
    -
      name: Originating repo checkout (e.g. public fork)
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    -
      name: Get changed markdown files
      uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v4.7.0
      id: changed-markdown-files
      with:
        files: '**/*.md'
    -
      name: Notify
      run: |
        echo "::notice::Detected some changed markdown files"
        echo "${{ steps.changed-markdown-files.outputs.all_changed_files }}"
